### ISSUE TITLE
layer.Message.sendReceipt don't sincronize with other clients

### ISSUE THREAD

**Issue by alanhoff** [layerhq/layer-websdk#57]
Hello folks, I have this scenario:

Browser 1 (as br1):
- User admin1 is instantiated with the WebSDK
- admin1 created a live query for listing conversations

Browser 2 (as br2):
- User admin1 is instantiated with the WebSDK
- admin1 created a live query for listing conversations

The problem I'm having occurs in the following order:
- user1 sends a message to admin1
- br1:admin1 sees that they have a conversation with `unreadCount: 1` and click on it
- br1:admin1 list all messages and trigger `.sendReceipt` for the unread one
- br1:admin1 live query gets updated, `unreadCount` is now `0` and the view is successfully updated
- br2:admin1 still sees the same conversation with `unreadCount: 1`
- br2:admin1 open the conversation but `sendReceipt` isn't triggered bc all messages are already read
- br2:admin1 keeps seeing an incorrect view with `unreadCount: 1` eternally

Even if I force a `sendReceipt` when `br2:admin1` lists all messages the conversation isn't updated.

Am I doing something wrong?

**Comment by michaelkantor** [comment]
We released something yesterday that may fix that.  Try an update and see if it persists... will dig deeper if it does.  Checkout release `WebSDK 1.0.6`

**Comment by alanhoff** [comment]
@michaelkantor I can confirm that the issue still persists with WebSDK 1.0.6, let me know if you need more information.

**Comment by michaelkantor** [comment]
Hey; sorry this one slipped off the radar.  Do you have a link and login and replication instructions you can email me?
